name: Build Unsigned Binaries
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-unsigned:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 90
    env:
      BUZZ_DISABLE_TELEMETRY: true
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
          - os: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Downgrade Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.0.0'
        if: matrix.os == 'macos-latest'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: uv sync

      - uses: AnimMouse/setup-ffmpeg@v1
        id: setup-ffmpeg
        with:
          version: ${{ matrix.os == 'macos-latest' && '80' || '8.0' }}

      - name: Bundle
        run: |
          if [ "$RUNNER_OS" == "macOS" ]; then
            brew install create-dmg
            uv run make bundle_mac_unsigned
          elif [ "$RUNNER_OS" == "Windows" ]; then
            cp -r ./dll_backup ./buzz/
            uv run make bundle_windows
          fi
        shell: bash

      - uses: actions/upload-artifact@v4
        with:
          name: Buzz-Unsigned-${{ runner.os }}
          path: |
            dist/Buzz*-windows.exe
            dist/Buzz*-mac.dmg
